services:
  kubo:
    image: ipfs/kubo:${KUBO_VERSION:-latest}
    ports:
      - 4001
      - 5001
      - 8080
    volumes:
      - ./ci/access-control-allow-all.sh:/container-init.d/001-access-control-allow-all.sh
  e2e:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      - IPFS_API_URL=http://kubo:5001
      - CUSTOM_GATEWAY_URL=http://kubo:8080
      - TEST_E2E=true
      - IPFS_COMPANION_VERSION=${IPFS_COMPANION_VERSION}
    volumes:
      - ./build:/home/node/app/build
