node(label: 'linux') {
  checkout scm
  sh 'docker build -t ipfs-companion .'
  sh 'docker run -i ipfs-companion yarn test'
  sh 'docker run -i -v $(pwd)/build:/usr/src/app/build ipfs-companion yarn build'
  archiveArtifacts artifacts: 'build/*.zip'
}
